[credentials]
ollama_api_key = e3ea50b942054edbb7100c735253413c.pRRK9yIQQN3-aFV1vnycEwGz

[models]
ollama_models = gpt-oss:120b-cloud, gpt-oss:20b, gemma4:31b-cloud

[settings]
language = arabic
# Choose: translate or summary
type = merge_feed
# Number of posts to keep per feed (default: 20)
max_posts = 20
# Merge all feeds into one XML file: yes or no
merge_feed = no
